---

- hosts: all
  gather_facts: yes
  become: true
  tasks:
    - debug: msg="done"

- hosts: localhost
  gather_facts: no
  become: true
  vars_files:  
    - ./defaults.yml
  vars:
    - ansible_kernel: "4.2.0-38-generic"
    - files_to_import:
        - "{{ osa_conf }}/user_secrets.yml"
        - "{{ osa_conf }}/openstack_user_config.yml"
        - "{{ osa_play }}/openstack_hosts/defaults/main.yml"
        - "{{ osa_play }}/os_horizon/defaults/main.yml"
        - "{{ osa_play }}/galera_client/defaults/main.yml"

  pre_tasks:

    - local_action: command uname -r
      register: uname
      
    - set_fact:
          ansible_kernel: "{{ uname.stdout | replace('\"', '') }}"
  
    - local_action: command ./scripts/osrel.sh
      register: osrel

    - set_fact:
          ostag: "{{ osrel.stdout | replace('\"', '') }}"
  
    - set_fact:
          openstack_release: "{{ ostag }}"

    - debug: var=groups['all']

  tasks:
  
    - include_vars: "{{ item }}"
      with_items: "{{ files_to_import }}"
      
    - template:
          src: ./templates/osa_vars.yml.j2
          dest: ./osa_vars.yml

    - template:
          src: ./templates/osa_groups.json.j2
          dest: ./osa_groups.json

    #- include_vars: ./osa_groups.json
    #- debug: var=osa_groups


