---
# Copyright 2015, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# install prereq packages to lxc containers
- name: installs prereq packages with aptitude
  apt: name={{ item }} state=present update_cache=true
  with_items: "{{ apt_packages }}"

- name: Add apt keys
  apt_key:
    url: "{{ item.url }}"
    state: "{{ item.state }}"
  with_items: logstash_apt_keys
  when: logstash_apt_keys is defined
  register: add_keys_url
  until: add_keys_url|success
  retries: 5
  delay: 2
  tags:
    - logstash-apt-keys
    - logstash-pre-install

- name: Add apt repositories
  apt_repository:
    repo: "{{ item.repo }}"
    state: "{{ item.state }}"
  with_items: logstash_apt_repos
  register: add_repos
  until: add_repos|success
  retries: 5
  delay: 2
  tags:
    - logstash-apt-repos
    - logstash-pre-install

