---
# Copyright 2016, IBM US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# opsmgr version
opsmgr_version: 0.9.9

# opsmgr directory
opsmgr_dir: "{{ playbook_dir }}/.."

# tweak use of pip
pipexec: pip
pipargs: ''

# name of sudoers file
sudoers_filename: opsmgr_sudoers

# internal database
db_name: opsmgr
mysql_root_user: root
mysql_root_password: passw0rd

# initializer for lxcnets list
lxcnets: []


#All variables below this point need to be defined for both the standalone
#and the OSA paths to work but they are only used in the OSA path

# lxc container networks
# defines additional networks to be created
container_networks:
  - name: mgmt
    bridge: "br-mgmt"
    interface: "eth1"
    netmask: "255.255.252.0"
    type: "veth"

address_pool: [ 172.29.236.41, 172.29.236.42, 172.29.236.43, 172.29.236.44, 172.29.236.45, 172.29.236.46, 172.29.236.47, 172.29.236.48, 172.29.236.49 ]

lxc_container_default_mtu: 1500
